---
title: "Your digital notebook"
author: "Mark Sterken"
date: "2026-02-04"
format:
  html:
    toc: true
    toc-depth: 3
    code-fold: true
    code-tools: true
editor: visual
execute:
  warning: false
  message: false
---

## Your digital notebook

### Introduction to day 3

Today we will continue with goal 1 (Built basic knowledge on using R and R studio) and goal 3 (Apply common statistical tools for inspecting and analyzing data). We will also start with goal 4 (Be able to document your code in a clear & concise way). You will find out that we've already covered this by requiring you to write a script. Now we'll add one more layer to it, the notebook.

New today, is that you get an assignment. In this assignment, you are expected to go over goal 5 \[(Apply the data-science cycle (load, inspect, ~~clean~~, analyse, present)\]. Also, this is not new, we've been doing it for the past two days.

As on the pervious days, we will be making use of a real data-case.

::: {.callout-tip appearance="simple"}
### Plant growth impairment by nematodes.

You already know that plant susceptibility to nematodes is a complex trait, with a lot of variation in susceptibility between individuals of the same species. This variation also exists for the dose-response relation between plants and nematodes. The data you will be using today is derived from a study by Jaap-Jan Willig, who used a camera platform to track the growth of 960 *A. thaliana* plants simultaneously[@Willig2023].

![The relationship between the inoculation density (P~i~) of *H. schachtii* and green canopy area (relative yield). Nine-day-old Arabidopsis seedlings were inoculated with 20 different densities of *H. schachtii* juveniles (0--100 J2s g^--1^ of dry sand) in 200 ml pots containing 200 g of dry sand. (A) Experimental set up and colour channel decomposition of photos to extract the green leaf surface from the images. (B) Average growth curve of Arabidopsis plants inoculated with different inoculum densities of *H. schachtii* from 0 to 21 dpi. Line fitting was based on a LOESS regression. The red box indicates the data that are used for fitting the Seinhorst yield loss equation (n=10--24). (C) Fitting according to the Seinhorst yield loss equation. Parameter values for Seinhorst's equation for the relationship between initial population density (P~i~) of *H. schachtii* and measured leaf surface area. P~i~ and tolerance limit (TSYLM) are expressed in *H. schachtii* (per g of dry sand) while, the minimal yield (m) is the lowest proportion of the maximum green canopy area (cm^2^) (Ymax) at 21 dpi. The goodness of fit of the model on the data is expressed as the coefficient of determination (R^2^).](Week1_day3_Willig.jpeg)

The goal of this research was to develop a platform that allowed us to track in real-time plant growth under below-ground biotic stress caused by nematode infection. Doing this experiment, we identified a compensation response where, at low levels of infection, plants perform better than in uninfected conditions. 
:::















